from fastapi import FastAPI, HTTPException
from sqlmodel import SQLModel, Field, Session, select
from datetime import datetime
from typing import Dict, Optional, List
from database import create_file_db, engine
from datetime import datetime

class Exercise(SQLModel,table=True):
	id : Optional[int] = Field(default=None, primary_key=True)
	exercise_name : str
	weight : float
	reps : int
	sets : int 
	date : datetime =  Field(default_factory=datetime.utcnow) 

class ExerciseCreate(SQLModel):
	exercise_name : str
	weight : float
	reps : int
	sets : int 


app = FastAPI()

@app.on_event("startup")
def create_db():
	create_file_db()

@app.get("/")
def health() -> Dict[str, str | float]:
	return {"health" : "active", "version" : 1.0}


@app.post("/workouts")
def post_workout(workout : ExerciseCreate) -> Exercise:
	'''
		Takes ExerciseCreate Object (without ID as it gets autogenerated)
		return the object after it has been taken 
	'''
	db_workout = Exercise.model_validate(workout)
	with Session(engine) as session:
		if workout.weight > 0 and workout.reps > 0 and workout.sets > 0:
			session.add(db_workout)
			session.commit()
			session.refresh(db_workout)
		else:
			raise HTTPException(status_code=400, detail="Weight, Set or reps are 0")
	return db_workout

@app.get("/workouts")
def get_workouts() -> List[Exercise]:
	'''
		Returns a list of Exercises
	'''
	with Session(engine) as session:
		results  = session.exec(select(Exercise))
		all_workouts = results.all()
		return all_workouts

@app.get("/workouts/{id}")
def get_workout_id(workout_id : int) -> Exercise:
	with Session(engine) as session:
		exercise = session.get(Exercise,workout_id)
		if exercise is None:
			raise HTTPException(status_code= 404, detail="Exercise with id not found")
		else:
			return exercise
		
@app.put("/workouts/{id}")
def update_workout_id(workout_id : int, new_workout_data : ExerciseCreate) -> Exercise:
	with Session(engine) as session:
		workout_to_update = session.get(Exercise,workout_id)
		if workout_to_update is None:
			raise HTTPException(status_code=404, detail="Workout ID does not exist")
		else:
			workout_to_update.exercise_name = new_workout_data.exercise_name
			workout_to_update.sets = new_workout_data.sets
			workout_to_update.reps = new_workout_data.reps
			workout_to_update.weight = new_workout_data.weight
			session.add(workout_to_update)
			session.commit()
			session.refresh(workout_to_update)
		return workout_to_update
	

@app.delete("/workouts/{id}")
def delete_workout(exercise_id : int) -> Exercise:
	with Session(engine) as session:
		delete_exercise = session.get(Exercise, exercise_id)
		if delete_exercise is None:
			raise HTTPException(status_code=404,detail="Exercise id not found!!!")
		session.delete(delete_exercise)
		session.commit()	
		return delete_exercise


